import IDENTITY_PROVIDER_METHODS_DEFINITIONS from './identityProvider';

export const IDENTITY_PROVIDER_METHODS = IDENTITY_PROVIDER_METHODS_DEFINITIONS;

export default {
  IDENTITY_PROVIDER_METHODS
};
